const DSM_ERRORS: Record<string, string> = {
  "1": "Token and amounts length differ",
  "2": "Too much slippage",
  "3": "Exchanger not found",
  "4": "Pool ids not found",
  "5": "Would unbalance Gyroscope",
  "6": "Vault already exists",
  "7": "Vault not found",
  "20": "X out of bounds",
  "21": "Y out of bounds",
  "22": "Product out of bounds",
  "23": "Invalid exponent",
  "24": "Out of bounds",
  "25": "Zero division",
  "26": "Add overflow",
  "27": "Sub overflow",
  "28": "Mul overflow",
  "29": "Div internal",
  "30": "Not authorized",
  "31": "Invalid argument",
  "32": "Key not found",
  "33": "Key frozen",
  "34": "Insufficient balance",
  "35": "Invalid asset",
  "40": "Asset not supported",
  "41": "Stale price",
  "42": "Negative price",
  "43": "Invalid message",
  "44": "WETH address not first",
  "45": "A short-term circuit breaker in the CPF oracle system has been triggered. This means that the protocol is less sure of what asset prices are right now and so temporarily disables minting and redeeming. Please try again later.",
  "46": "Not enough TWAPs",
  "47": "Zero price TWAP",
  "48": "Invalid number of weights",
  "51": "A vault has all stablecoins off peg",
  "52": "The reserve follows a certain logic to keep all included assets balanced. Currently, no further mints for your chosen asset are possible, as this asset is already overrepresented. Select a different mint asset or try again later.",
  "53": "The reserve follows a certain logic to keep all included assets balanced. Currently, no further redemptions against your chosen asset are possible, as this asset is already underrepresented. Select a different redemption asset or try again later.",
  "54": "Amount and price length differ",
  "55": "Token prices too small",
  "56": "Trying to redeem more than the vault contains",
  "57": "Caller not motherboard",
  "58": "Caller not reserve manager",
  "60": "Vault flow too high",
  "61": "Operation succeeds but safety mode activated. As a protective measure, safety mode has been activated by a circuit breaker. The DSM is temporarily disabled for the chosen asset and operation.",
  "62": "Oracle guardian time limit",
  "63": "Not enough flow data",
  "64": "Mint allowance exceeded",
  "65": "As a protective measure, safety mode has been activated by a circuit breaker. The DSM is temporarily disabled for the chosen asset and operation.",
  "100": "Redeem amount bug",
};
export default DSM_ERRORS;
